"""unique payment provider_ref

Revision ID: c8ed9be90973
Revises: f313e8959f62
Create Date: 2026-09-11 20:12:26.916463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ed9be90973'
down_revision: Union[str, Sequence[str], None] = 'f313e8959f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_payments_provider_provider_ref', 'payments', ['provider', 'provider_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payments_provider_provider_ref', 'payments', type_='unique')
    # ### end Alembic commands ###
